### ISSUE TITLE
🎯 What can I work on ?

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openbeautyfacts#75]
### What
- Please see the tracker issue on the server: https://github.com/openfoodfacts/openfoodfacts-server/issues/5505. It proposes options to integrate Open Beauty Facts within Open Food Facts, and make it transparent for users.
- Android: https://github.com/openfoodfacts/openfoodfacts-androidapp/issues/4168 and https://github.com/openfoodfacts/openfoodfacts-androidapp/issues/4165
- iOS (currently the very old cordova app): https://github.com/openfoodfacts/openfoodfacts-cordova-app
- Flutter: We need to get Flutter/Dart support, this is the future to ensure we can build OBF at low marginal cost.
- API: https://github.com/openfoodfacts/api-documentation (There's an Open Beauty Facts section)
- Robotoff: we'd need to deploy and get it running for Open Beauty Facts

```[tasklist]
### Mobile
- [ ] Ensure openfoodfacts-dart can handle cosmetics
- [ ] Ensure smooth-app can handle cosmetics
- [ ] openfoodfacts/openbeautyfacts#44
- [ ] openfoodfacts/openfoodfacts-infrastructure#634
- [ ] openfoodfacts/openbeautyfacts#67
- [x] openfoodfacts/openbeautyfacts#1
- [x] openfoodfacts/openbeautyfacts#5 
- [x] openfoodfacts/openbeautyfacts#43
- [x] openfoodfacts/openbeautyfacts#51
- [x] openfoodfacts/openbeautyfacts#52 
- [x] openfoodfacts/openbeautyfacts#53 
- [x] openfoodfacts/openbeautyfacts#73 
```

```[tasklist]
### Data quality
- [x] openfoodfacts/openbeautyfacts#54 
```

```[tasklist]
### Web
- [ ] openfoodfacts/openbeautyfacts#56
- [ ] openfoodfacts/openbeautyfacts#7
- [ ] openfoodfacts/openbeautyfacts#8
- [ ] openfoodfacts/openbeautyfacts#15
- [ ] openfoodfacts/openbeautyfacts#20
- [ ] openfoodfacts/openbeautyfacts#22
- [ ] openfoodfacts/openbeautyfacts#24
- [ ] openfoodfacts/openbeautyfacts#25
- [ ] openfoodfacts/openbeautyfacts#26
- [x] openfoodfacts/openbeautyfacts#5
- [x] openfoodfacts/openbeautyfacts#6
- [x] openfoodfacts/openbeautyfacts#9
- [x] openfoodfacts/openbeautyfacts#11
- [x] openfoodfacts/openbeautyfacts#17
- [x] openfoodfacts/openbeautyfacts#18
- [x] openfoodfacts/openbeautyfacts#23
- [x] openfoodfacts/openbeautyfacts#28
- [x] openfoodfacts/openbeautyfacts#46
- [ ] openfoodfacts/openbeautyfacts#37
- [ ] openfoodfacts/openbeautyfacts#38
- [ ] openfoodfacts/openbeautyfacts#39
- [ ] openfoodfacts/openbeautyfacts#41
- [ ] openfoodfacts/openbeautyfacts#42
- [ ] openfoodfacts/openbeautyfacts#45
- [ ] openfoodfacts/openbeautyfacts#47
- [ ] openfoodfacts/openbeautyfacts#48
```
```[tasklist]
### bugs
- [x] openfoodfacts/openbeautyfacts#58 
- [ ] openfoodfacts/openbeautyfacts#59
- [ ] openfoodfacts/openbeautyfacts#60 
- [ ] openfoodfacts/openbeautyfacts#64
- [ ] openfoodfacts/openbeautyfacts#66
- [ ] openfoodfacts/openbeautyfacts#68 
```

```[tasklist]
### Improve the Open Beauty Facts API and its documentation
- [x] openfoodfacts/openbeautyfacts#61 
```

```[tasklist]
### Ensure we don't loose SEO opportunities
- [ ] openfoodfacts/openbeautyfacts#49 
- [ ] openfoodfacts/openbeautyfacts#65
```

```[tasklist]
### Translations
- [ ] openfoodfacts/openbeautyfacts#50 
```

```[tasklist]
### Data model
- [x] openfoodfacts/openbeautyfacts#31
- [ ] openfoodfacts/openbeautyfacts#34
```

```[tasklist]
### Value-added
- [ ] openfoodfacts/openbeautyfacts#35
- [ ] openfoodfacts/openbeautyfacts#36 
- [ ] openfoodfacts/openbeautyfacts#57
- [ ] openfoodfacts/openbeautyfacts#69
```

```[tasklist]
### Web content
- [ ] openfoodfacts/openbeautyfacts#12 
- [ ] openfoodfacts/openfoodfacts-web#905 
- [ ] openfoodfacts/openbeautyfacts#10 
- [ ] openfoodfacts/openbeautyfacts#13 
- [ ] openfoodfacts/openbeautyfacts#14 
- [ ] openfoodfacts/openbeautyfacts#16
- [ ] openfoodfacts/openbeautyfacts#19
```

```[tasklist]
#### AI/Robotoff
- [ ] openfoodfacts/openbeautyfacts#3 
- [ ] openfoodfacts/openbeautyfacts#27
```

```[tasklist]
### Promotion
- [ ] openfoodfacts/openbeautyfacts#29
- [ ] openfoodfacts/openbeautyfacts#30 
- [ ] openfoodfacts/openbeautyfacts#32
- [ ] openfoodfacts/openbeautyfacts#37 
- [x] openfoodfacts/openbeautyfacts#40 
```

```[tasklist]
### Moderation
- [x] openfoodfacts/openbeautyfacts#33
```

```[tasklist]
### Devops
- [x] openfoodfacts/openbeautyfacts#70 
- [ ] openfoodfacts/openbeautyfacts#71 
- [ ] openfoodfacts/openfoodfacts-web#904
```

```[tasklist]
#### Visual assets
- [x] openfoodfacts/openbeautyfacts#74
```
